[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/api/send-welcome"
  to = "/.netlify/functions/send-welcome"
  status = 200
